### ISSUE TITLE
Deployment pipeline failed on Streamline icon

### ISSUE THREAD

**Issue by tomexx** [webalys-hq/streamlinehq-npm#47]
Hi there,

we are experiencing a problem as we aren't able to run a deployment pipeline b/c of Streamline icons cannot be resolved.

```
./src/components/modules/navigation/HeaderMenu.tsx
Module not found: Can't resolve '@streamlinehq/streamlinehq/img/streamline-bold/social-instagram-Nc3WWa.svg' in '/usr/src/app/src/components/modules/navigation'
./src/components/modules/navigation/HeaderMenu.tsx
Module not found: Can't resolve '@streamlinehq/streamlinehq/img/streamline-bold/social-media-facebook-1-LXc7gT.svg' in '/usr/src/app/src/components/modules/navigation'
```

**Comment by mkowal7** [comment]
Update the package to the latest version. I had the same problem as you

**Comment by cbrwizard** [comment]
Thank you for reporting this, we're aware of the issue and planning to resolve it soon. Our own CI is impacted by this as we also use this package internally.

**Comment by woeterman94** [comment]
Using version 3.0.4 seems to work 
   ` "@streamlinehq/streamlinehq": "^3.0.4",
`

**Comment by hanneskuettner** [comment]
For me this results in `Error: Streamline is unavailable, please try again later`.
Might be a sporadic server problem that doesn't impact everyone at all times?

**Comment by sorlovsky** [comment]
Seeing the same behavior as @hanneskuettner , our builds are failing about 50% of the time with the error specified above.

**Comment by cbrwizard** [comment]
The issue has been resolved now. I sincerely apologize for the issue caused. I personally know how frustrating it is.

Here is what happened:
- Streamline is in the process of migrating to better backend. Our website has already migrated to it, next steps were to move other clients: npm, figma plugin, sketch plugin
- 3.0.4 update to npm was about pointing it to new backend. Pointing to a new backend isn't a breaking change, hence the minor version update. I expected everything to work as usual and nobody would even notice the change.
- However, it didn't go well. The npm installation endpoint turned out to be not optimized and new backend wasn't ready for that. Npm installation requests led to whole Streamline backend going down frequently. At first I thought that it's a temporary issue but it kept getting worse as more and more users have switched to 3.0.4.
- When I found out about the issue I could not unpublish 3.0.4 package because it was already being used by some projects and it stopped the `npm unpublish` command. Oops.
- What's more, previous backend also went down because of an unexpected misconfiguration issue which went unnoticed because our error reporting system is also malfunctioning. That led to users of npm 3.0.3 not being able to use the package and led them to updating to 3.0.4 which led them directly to another trap.

Afterwards, I've started fixin'. The following work has been done:
- I have revived old backend, so that 3.0.3 users can keep using it.
- I have optimized npm installation endpoint so that now it's 65% faster. I basically put some data into db instead of generating it on the fly and it works. I should've done that earlier.

What else Streamline should do:
- Improve our alerts & logging system to be able to detect & fix endpoints which cause performance issues
- Setup a reverse proxy for old backend so that requests to it get redirected to the new one

Once again, I greatly appreciate your patience and thank you for using Streamline

**Comment by sorlovsky** [comment]
@cbrwizard hello, I want to report that one of our engineers is still receiving errors trying to pull in `3.0.4` can you provide any guidance? 
```
Error: Streamline is unavailable, please try again later
```

**Comment by cbrwizard** [comment]
@sorlovsky sorry to hear that. NPM installation endpoint still isn't perfect and sometimes works slowly. We're working on improving our database to speed this up as it impacts the whole website. Meanwhile we have cache in place and if the first request fails please try again in a minute: it should use the cached version which works faster.
